#!/usr/bin/env python3
"""Cursor's half of `version_drift.py`: is the Cursor install current, and has Cursor itself moved?

Called by `session_orientation.py --harness cursor` in place of `version_drift.check()`, which
reads Claude Code's install and would say nothing true about Cursor's (B57, v1.65.0).

FOUR FINDINGS, EACH ONE LINE, EACH WARN-ONLY. Nothing here installs, deletes or refreshes.

  1. Cursor's cairn and Claude Code's cairn are different versions on THIS machine. One release
     ships both (`tools/build_cursor.py` copies the version), so a mismatch means one harness was
     refreshed and the other was not. Silent when Claude Code has no cairn installed.
  2. A hand-written `~/.cursor/skills/{next,wrap}` is present. Those predate the adapter, are
     generated from nothing, and on one work laptop still describe a file contract cairn
     abandoned (QUEUE.md). They are what B57 exists to retire.
  3. A Claude-format cairn sits in Cursor's plugin cache -- a folder with `.claude-plugin/` and no
     `.cursor-plugin/`, put there by Cursor's third-party import. Measured 2026-09-26: v1.53.4
     from the old repository URL, with hooks Cursor cannot run. Uninstalling it in Cursor did
     NOT remove the folder (nor the marketplace clone beside it), and Cursor records installs as
     opaque ids per workspace, so nothing on disk says whether it is still installed. The line
     therefore names the folder and says what to do in each case, and falls silent once the
     folder is gone -- a warning with no way to clear it would be noise.
  4. The generated rule's embedded version is not this plugin's -- a hand edit, or a build that
     was not re-run. `tools/build_cursor.py --check` stops that in the source repo; this catches
     an install that was patched by hand.

AND ONE TRIGGER: CURSOR ITSELF CHANGED. Some of what cairn cannot do in Cursor is missing from
Cursor, not from cairn (archiving a chat, reading the chat list). A calendar reminder to re-test
would fire mostly on no change, so this fires on the change instead: the last-seen Cursor version
and the list of Cursor's built-in skills (`~/.cursor/skills-cursor/`) are kept in the state dir,
and a difference prints one line pointing at `cursor/gaps.md`. The first run records silently --
there is nothing to compare against, and a line that says so is noise. The `rename_chat` tool the
Cursor wrap uses was found exactly this way: it was already sitting in `skills-cursor/`.

Never raises. Returns None when there is nothing to say.
"""
from __future__ import annotations

import json
import os
import re
from pathlib import Path

try:
    import version_drift
except Exception:                      # pragma: no cover - never fail an orientation
    version_drift = None               # type: ignore[assignment]

PLUGIN = Path(__file__).resolve().parents[1]
CURSOR_MANIFEST = PLUGIN / ".cursor-plugin" / "plugin.json"
GENERATED_RULE = PLUGIN / "cursor" / "rules" / "cairn.mdc"
GAPS = "cursor/gaps.md"
LEGACY_SKILLS = ("next", "wrap")

# `<!-- GENERATED by tools/build_cursor.py ... cairn v1.65.0 ... -->`, written by build_cursor.
_RULE_VERSION_RE = re.compile(r"GENERATED by tools/build_cursor\.py.*?cairn v([0-9][0-9.]*)")

# Kept beside the `_sessions` stamps. Not a per-project `state_dir()` slug (those always end in
# ten hex digits), so nothing that globs project state directories ever reads it.
SEEN_SUBDIR = "_cursor"
SEEN_FILE = "seen.json"


def cursor_home() -> Path:
    override = os.environ.get("CAIRN_CURSOR_HOME", "").strip()
    return Path(override).expanduser() if override else Path.home() / ".cursor"


def _state_file() -> Path | None:
    base = os.environ.get("CLAUDE_CONFIG_DIR") or (Path.home() / ".claude")
    directory = Path(base) / "reentry-state" / SEEN_SUBDIR
    try:
        directory.mkdir(parents=True, exist_ok=True)
    except OSError:
        return None
    return directory / SEEN_FILE


def _json_version(path: Path) -> str | None:
    try:
        return str(json.loads(path.read_text(encoding="utf-8")).get("version") or "") or None
    except Exception:
        return None


def cursor_plugin_version() -> str | None:
    return _json_version(CURSOR_MANIFEST)


def _claude_plugin_version() -> str | None:
    try:
        return version_drift._installed_version() if version_drift else None
    except Exception:
        return None


def _harness_mismatch() -> str | None:
    mine, claude = cursor_plugin_version(), _claude_plugin_version()
    if not mine or not claude or mine == claude:
        return None
    newer = version_drift.compare_versions(mine, claude) if version_drift else None
    if newer == 1:
        fix = "update Claude Code's: `claude plugin update cairn@superbole`"
    else:
        fix = "refresh the superbole marketplace in Cursor's plugin settings"
    return (f"⚠ cairn in Cursor is v{mine}, but Claude Code on this machine has v{claude} — "
            f"{fix}. One release ships both, so a mismatch is a refresh that did not happen.")


def _legacy_skills(home: Path) -> str | None:
    found = [n for n in LEGACY_SKILLS if (home / "skills" / n / "SKILL.md").is_file()]
    if not found:
        return None
    where = ", ".join(f"~/.cursor/skills/{n}" for n in found)
    return (f"⚠ hand-written {where} {'is' if len(found) == 1 else 'are'} still installed. "
            f"They predate cairn's Cursor adapter and are generated from nothing, so they drift; "
            f"cairn's skills are `cairn-next` / `cairn-wrap`. Delete them when you are ready — "
            f"nothing here removes them.")


def _stale_import(home: Path) -> str | None:
    found = []
    try:
        for manifest in (home / "plugins" / "cache").glob("*/cairn/*/.claude-plugin/plugin.json"):
            folder = manifest.parent.parent
            if not (folder / ".cursor-plugin").is_dir():
                found.append((_json_version(manifest) or "?", folder))
    except OSError:
        return None
    if not found:
        return None
    listed = "; ".join(f"v{v} at {folder}" for v, folder in sorted(found))
    return (f"⚠ a Claude-format cairn is in Cursor's plugin cache ({listed}), from its "
            f"third-party import. Its hooks cannot run in Cursor. If Cursor's plugin list no "
            f"longer shows it, it is left over from an uninstall — delete that folder. If it "
            f"still shows, uninstall it there first, then delete the folder.")


def _rule_mismatch() -> str | None:
    mine = cursor_plugin_version()
    try:
        head = GENERATED_RULE.read_text(encoding="utf-8")[:2000]
    except OSError:
        return None
    match = _RULE_VERSION_RE.search(head)
    if not mine or not match or match.group(1) == mine:
        return None
    return (f"⚠ cairn's Cursor rule was generated for v{match.group(1)} but the plugin is "
            f"v{mine} — the rule was edited by hand or not rebuilt. Rules in front of this "
            f"session may be out of date.")


def _builtin_skills(home: Path) -> list[str]:
    try:
        return sorted(p.name for p in (home / "skills-cursor").iterdir() if p.is_dir())
    except OSError:
        return []


def _cursor_changed(home: Path, cursor_version: str) -> str | None:
    """One line when Cursor's version or built-in skills differ from last time; records now."""
    state = _state_file()
    if state is None:
        return None
    skills = _builtin_skills(home)
    try:
        seen = json.loads(state.read_text(encoding="utf-8"))
    except Exception:
        seen = None
    # A run from the `cairn-orient` skill has no payload, so often no version: keep the last one
    # rather than forget it, or the next real change would compare against "".
    kept = cursor_version or (str(seen.get("cursor_version") or "") if isinstance(seen, dict) else "")
    now = {"cursor_version": kept, "skills": skills}
    try:
        state.write_text(json.dumps(now), encoding="utf-8")
    except OSError:
        return None
    if not isinstance(seen, dict):
        return None                     # first run: nothing to compare against, say nothing
    parts = []
    old_version = str(seen.get("cursor_version") or "")
    if cursor_version and old_version and cursor_version != old_version:
        parts.append(f"Cursor {old_version} → {cursor_version}")
    added = sorted(set(skills) - set(seen.get("skills") or []))
    if added and seen.get("skills"):
        parts.append("new built-in skills: " + ", ".join(added))
    if not parts:
        return None
    return (f"Cursor changed since the last session ({'; '.join(parts)}). Something cairn cannot "
            f"do in Cursor today may now be possible — re-run the probes in `{GAPS}` in the "
            f"plugin and file any that pass as backlog items.")


def check(root: Path | None = None, cursor_version: str = "") -> str | None:
    """Lines for the agent, or None. `cursor_version` comes from the hook payload when there is
    one; `CURSOR_VERSION` (exported to hook commands) is the fallback."""
    home = cursor_home()
    version = cursor_version or os.environ.get("CURSOR_VERSION", "")
    lines = []
    for finding in (_harness_mismatch, lambda: _legacy_skills(home),
                    lambda: _stale_import(home), _rule_mismatch,
                    lambda: _cursor_changed(home, version)):
        try:
            line = finding()
        except Exception:
            line = None
        if line:
            lines.append(line)
    return "\n\n".join(lines) if lines else None


if __name__ == "__main__":
    try:
        import sys
        sys.stdout.reconfigure(encoding="utf-8")     # a Windows console would choke on the ⚠
    except Exception:
        pass
    print(check() or "cursor drift: nothing to report")
