#!/usr/bin/env python3
"""Generate cairn's Cursor artefacts from the Claude Code sources. `--check` says whether they are current.

    python plugins/cairn/tools/build_cursor.py            # write
    python plugins/cairn/tools/build_cursor.py --check    # exit 1 if anything is stale

WHY THIS EXISTS (B57, v1.65.0). Before it, Cursor's side of cairn was a pair of skills written
by hand on 2026-09-04. By 2026-09-26 three copies existed on two machines and no two of them
matched; one still described a file contract cairn had dropped. The failure was never the
content -- it was that a second copy existed at all, with nothing tying it to the first.

So the rule is one source, generated artefacts, and a test that refuses a stale one:

  rules/CLAUDE.md + cursor/preamble.md  ->  cursor/rules/cairn.mdc   (always-applied Cursor rule)
  .claude-plugin/plugin.json            ->  .cursor-plugin/plugin.json (same version, Cursor paths)

`install_rules.py` is the other consumer of `rules/CLAUDE.md` (it writes the block in
`~/.claude/CLAUDE.md`). Neither rewrites the rules text: Cursor reads the Claude wording through
the substitution table in `cursor/preamble.md`. Forking the text is the one thing this must never
do.

`tools/test_cursor_build.py` runs `--check`, so a version bump that forgets to rebuild cannot pass
the suite -- that is the whole of the lockstep between the two harnesses.

What is NOT generated: `cursor/skills/*` (thin, hand-written pointers at `skills/*/SKILL.md`),
`cursor/hooks.json` and `cursor/gaps.md`. They change when Cursor changes, not when cairn does.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

PLUGIN = Path(__file__).resolve().parents[1]
RULES = PLUGIN / "rules" / "CLAUDE.md"
PREAMBLE = PLUGIN / "cursor" / "preamble.md"
CLAUDE_MANIFEST = PLUGIN / ".claude-plugin" / "plugin.json"
CURSOR_MANIFEST = PLUGIN / ".cursor-plugin" / "plugin.json"
RULE_OUT = PLUGIN / "cursor" / "rules" / "cairn.mdc"

CURSOR_DESCRIPTION = (
    "Never lose your place between sessions. Relays the project's NEXT.md queue, due watches and "
    "inbox at the start of a chat, and provides cairn-next to re-enter work and cairn-wrap to end "
    "a session so the next one starts from disk. The same plugin, and the same files, as cairn "
    "for Claude Code."
)


def _read(path: Path) -> str:
    return path.read_bytes().decode("utf-8").replace("\r\n", "\n")


def _version() -> str:
    return str(json.loads(_read(CLAUDE_MANIFEST))["version"])


def render_rule() -> str:
    rules, preamble = _read(RULES), _read(PREAMBLE)
    digest = hashlib.sha256((preamble + "\0" + rules).encode("utf-8")).hexdigest()[:12]
    return (
        "---\n"
        "description: cairn session re-entry rules (generated; the source is rules/CLAUDE.md)\n"
        "alwaysApply: true\n"
        "---\n"
        f"<!-- GENERATED by tools/build_cursor.py from cursor/preamble.md + rules/CLAUDE.md — "
        f"cairn v{_version()}, sources sha256 {digest}. Do not edit: edit the sources and "
        f"rebuild, or the next build overwrites it. -->\n\n"
        + preamble.rstrip("\n") + "\n\n---\n\n" + rules.rstrip("\n") + "\n"
    )


def render_manifest() -> str:
    claude = json.loads(_read(CLAUDE_MANIFEST))
    manifest = {
        "name": claude["name"],
        "description": CURSOR_DESCRIPTION,
        "version": claude["version"],
        "author": claude.get("author", {}),
        "homepage": claude.get("homepage", ""),
        "license": claude.get("license", ""),
        # Explicit paths REPLACE folder discovery (cursor.com/docs/reference/plugins), which is
        # what keeps Cursor away from the Claude-format `hooks/hooks.json` and `skills/`.
        "rules": "./cursor/rules/",
        "skills": "./cursor/skills/",
        "hooks": "./cursor/hooks.json",
    }
    return json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"


OUTPUTS = ((RULE_OUT, render_rule), (CURSOR_MANIFEST, render_manifest))


def stale() -> list[Path]:
    out = []
    for path, render in OUTPUTS:
        try:
            current = _read(path)
        except OSError:
            current = None
        if current != render():
            out.append(path)
    return out


def main(argv: list[str]) -> int:
    if "--check" in argv:
        bad = stale()
        for path in bad:
            print(f"STALE: {path.relative_to(PLUGIN).as_posix()} — run tools/build_cursor.py")
        if not bad:
            print("cursor artefacts: current")
        return 1 if bad else 0
    for path, render in OUTPUTS:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(render().encode("utf-8"))
        print(f"wrote {path.relative_to(PLUGIN).as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
